import { withCourseExperience } from "./experiences/definitions.js";
import { PATHWAY_EDGES } from "./pathway-edges.js";
import { adventure } from "./adventure-definition.js";
import { buildMetronome } from "./adventure/metronome-world.js";
const course = adventure({
  id: "metronome-hall",
  pathwayEdges: PATHWAY_EDGES["metronome-hall"],
  name: "Metronome Hall",
  description:
    "Drive the rhythm of a gigantic music box: pendulums, tappets and hammer gates answer a shared mechanical beat.",
  points: [
    [-260, 8, -210],
    [-85, 10, -260],
    [130, 14, -190],
    [280, 20, -60],
    [215, 24, 100],
    [65, 30, 150],
    [135, 42, 270],
    [-50, 40, 320],
    [-225, 25, 250],
    [-170, 14, 80],
    [-290, 8, -20],
    [-340, 8, -140],
  ],
  places: [
    [0, "workshop", "MUSIC BOX WORKSHOP", "wood"],
    [2, "tappets", "TAPPET AVENUE", "metal"],
    [4, "hall", "PENDULUM HALL", "wood", 11],
    [6, "bells", "BELL TOWER", "metal", 11],
    [8, "hammers", "HAMMER GALLERY", "wood", 11],
    [10, "home", "WINDING KEY RETURN", "wood"],
  ],
  palette: ["#d9b99b", "#bb9fc2", "#66536b", "#e3b977", "#9a748f"],
  targetLength: 1850,
  buildWorld: buildMetronome,
  staticBake: true,
  shortcut: {
    section: 5,
    startFraction: 0.15,
    endFraction: 0.7,
    extraWidth: 0.01,
    material: "wood",
  },
  verges: [
    {
      section: 2,
      startFraction: 0.08,
      endFraction: 0.86,
      side: -1,
      extraWidth: 5,
      material: "wood",
      grip: 12,
      driveable: true,
      drag: 1.15,
    },
  ],
  theme: {
    sky: "#d9b99b",
    fog: "#bd9db4",
    ground: "#66536b",
    road: "#e3b977",
    shoulder: "#a68099",
    hemisphere: "#c8d4ed",
    ambientGround: "#775971",
    ambientIntensity: 0.72,
    interiorAmbientScale: 0.9,
    sun: "#ffe6b7",
    sunIntensity: 2.8,
    sunPosition: [-75, 80, 60],
    exposure: 1.15,
    terrain: "wood",
    groundHeight: -22,
    fogFar: 900,
    cameraFar: 1150,
    lightVolume: {
      resolution: 128,
      columns: 3,
      rows: 2,
      heights: [-20, 0, 15, 30, 45, 65],
      strength: 1.2,
    },
  },
  ambientSources: [
    { section: 0, fraction: 0.5, offset: -30, kind: "wood", range: 75, volume: 0.09 },
    { section: 1, fraction: 0.5, offset: 60, kind: "engine", range: 120, volume: 0.1 },
    { section: 3, fraction: 0.5, offset: 25, kind: "wood", range: 120, volume: 0.12 },
  ],
  pendulums: [
    { section: 1, fraction: 0.25, period: 2, phase: 0 },
    { section: 1, fraction: 0.7, period: 2, phase: Math.PI },
    { section: 2, fraction: 0.25, period: 2, phase: 0 },
    { section: 2, fraction: 0.7, period: 2, phase: Math.PI },
    { section: 3, fraction: 0.5, period: 2, phase: 0 },
    { section: 4, fraction: 0.3, period: 2, phase: Math.PI },
    { section: 4, fraction: 0.72, period: 2, phase: 0 },
  ],
});

export default withCourseExperience(course);
