import buildWorld from "./neon-harbor-world.js";

// Port Lumen: a waterfront loop from the promenade, through the city and
// market, over the suspension bridge, and back via the industrial island.
export default {
  id: "neon-harbor",
  name: "Neon Harbor",
  description: "Port Lumen after dark: switchback streets, bridge traffic, cargo lanes and a race ferry.",
  targetLength: 1900,
  // Thirty ordered controls give each district a clean arc range while keeping
  // the bridge climb and broad waterfront turns smooth under the shared spline.
  controls: [
    [-144.49, 2, -188.79],
    [-96.78, 2, -194.23],
    [-41.69, 2, -192.71],
    [12.1, 2, -181.33],
    [59.77, 2, -162.65],
    [99.18, 2, -142.22],
    [127.62, 3, -121.52],
    [143.12, 4, -90.11],
    [159.08, 5, -51.62],
    [172.63, 5, -12.3],
    [188.28, 5, 22.06],
    [199.84, 6, 55.48],
    [196.45, 7, 89.66],
    [178.59, 13, 122.1],
    [153.37, 22, 148.54],
    [120.64, 28, 168.29],
    [75.34, 28, 185.16],
    [22.04, 23, 191.55],
    [-28.39, 12, 179.09],
    [-68.8, 5, 153.36],
    [-103.29, 4, 124.28],
    [-140.52, 4, 96.77],
    [-173.41, 4, 65.99],
    [-196.39, 3, 29.86],
    [-213.89, 3, -8.04],
    [-230.76, 2, -48.07],
    [-239.47, 2, -94.86],
    [-231.45, 2, -139.8],
    [-208.87, 2, -169.47],
    [-179.84, 2, -182.47],
  ],
  sections: [
    {
      controlIndex: 0,
      id: "promenade",
      name: "HARBOR PROMENADE",
      hint: "Ride the waterfront sweep · Port Lumen ahead",
      halfWidth: 10,
      material: "asphalt",
      color: "#7af1e6",
    },
    {
      controlIndex: 4,
      id: "downtown",
      name: "DOWNTOWN SWITCHBACKS",
      hint: "Link the city turns · keep an eye on the service cut",
      halfWidth: 7.8,
      material: "asphalt",
      color: "#ed8bc6",
    },
    {
      controlIndex: 8,
      id: "market",
      name: "NIGHT MARKET",
      hint: "Thread the warm-lit stalls · bridge towers ahead",
      halfWidth: 8,
      material: "stone",
      color: "#ffbf72",
    },
    {
      controlIndex: 12,
      id: "bridge",
      name: "PORT LUMEN BRIDGE",
      hint: "Climb into the harbor view · watch the traffic",
      halfWidth: 11,
      material: "asphalt",
      color: "#8ad9ff",
    },
    {
      controlIndex: 18,
      id: "cargo",
      name: "CARGO TERMINAL",
      hint: "Take the powered belt · cranes and containers",
      halfWidth: 9.5,
      material: "concrete",
      color: "#ffd36c",
    },
    {
      controlIndex: 21,
      id: "ferry",
      name: "RACE FERRY",
      hint: "Enter the vehicle deck · hold your line",
      halfWidth: 9.5,
      material: "concrete",
      color: "#e2a5ff",
    },
    {
      controlIndex: 24,
      id: "seawall",
      name: "SOUTH SEAWALL",
      hint: "Follow the lighthouse · waterfront cut inside",
      halfWidth: 9.5,
      material: "stone",
      color: "#72dfcf",
    },
    {
      controlIndex: 27,
      id: "boulevard",
      name: "NEON BOULEVARD",
      hint: "One last drift · the harbor comes around again",
      halfWidth: 11,
      material: "asphalt",
      color: "#c4a5ff",
    },
  ],
  // Optional maintenance hops remain on the continuous road. The bridge joint
  // plate occupies only the signed lane interval specified by its metadata.
  ramps: [
    { section: 0, fraction: 0.76, halfLength: 6, height: 0.6, offset: -6.3, halfWidth: 2 },
    { section: 3, fraction: 0.66, halfLength: 6, height: 0.55, offset: -6.5, halfWidth: 2 },
    { section: 7, fraction: 0.79, halfLength: 6, height: 0.6, offset: 6.5, halfWidth: 2 },
  ],
  bridgeJoint: { section: 3, fraction: 0.66, length: 1.2, hop: { offset: -6.5, halfWidth: 2 } },
  pads: [
    { section: 0, fraction: 0.72, offset: -6.3, duration: 0.8 },
    { section: 3, fraction: 0.86, offset: 0, duration: 0.75 },
    { section: 6, fraction: 0.42, offset: 5.1, duration: 0.7 },
    ...[0.3, 0.45, 0.6].map((fraction) => ({ section: 7, fraction, offset: -6.2, duration: 0.7 })),
  ],
  itemRows: [
    { section: 0, fraction: 0.28 },
    { section: 1, fraction: 0.14 },
    { section: 1, fraction: 0.88 },
    { section: 2, fraction: 0.58, offsets: [-10.8, -7, 0, 7] },
    { section: 3, fraction: 0.15 },
    { section: 4, fraction: 0.12 },
    { section: 4, fraction: 0.86 },
    { section: 5, fraction: 0.12, offsets: [-11.5, -8, 0, 8] },
    { section: 5, fraction: 0.7 },
    { section: 7, fraction: 0.48 },
  ],
  // The downtown cut and seawall rough line are ordered extensions of the
  // normal road, not disconnected routes.
  shortcut: {
    section: 1,
    startFraction: 0.34,
    endFraction: 0.69,
    extraWidth: 5,
    material: "paving",
    drag: 1.22,
  },
  verges: [
    {
      section: 2,
      startFraction: 0.22,
      endFraction: 0.74,
      side: -1,
      extraWidth: 5,
      material: "paving",
      grip: 10.2,
      drag: 0.78,
    },
    {
      section: 6,
      startFraction: 0.25,
      endFraction: 0.56,
      side: 1,
      extraWidth: 4,
      material: "paving",
      grip: 9.8,
      drag: 1.2,
    },
    {
      section: 5,
      startFraction: 0.03,
      endFraction: 0.21,
      side: -1,
      extraWidth: 4,
      material: "paving",
      grip: 11,
      drag: 0.82,
    },
  ],
  elevated: [
    { section: 3, startFraction: 0.12, endFraction: 0.9 },
  ],
  surfaces: [
    { section: 4, startFraction: 0.34, endFraction: 0.72, material: "concrete", grip: 12 },
  ],
  // Course-specific world feature descriptors consumed by the matching shared
  // systems when present. Fractions are local to their section.
  traffic: {
    section: 3,
    startFraction: 0.22,
    endFraction: 0.72,
    lanes: [1.5, 6],
    clearLane: -6.5,
    speed: 13.5,
    spacing: [45, 65],
    count: 4,
    kinds: ["sedan", "sedan", "van", "truck"],
  },
  conveyor: {
    section: 4,
    startFraction: 0.3,
    endFraction: 0.5,
    offset: 0,
    speed: 5,
    blendDistance: 3,
    fullWidth: true,
  },
  worldEvents: {
    lapTwoShip: { section: 3, fraction: 0.49, onceOnLap: 2, direction: -1 },
  },
  hazard: {
    section: 4,
    fraction: 0.84,
    kind: "cargo-shuttle",
    label: "CARGO SHUTTLE · KEEP LEFT",
    parkOffset: 12,
    minOffset: 0,
    halfWidth: 1.35,
    halfLength: 2.15,
    safeLane: -5.5,
    activation: 30,
    period: 12,
    warningSeconds: 2,
  },
  theme: {
    terrain: "concrete",
    sky: "#111d3e",
    fog: "#24365a",
    ground: "#3e5269",
    road: "#bdcce1",
    shoulder: "#829bb9",
    hemisphere: "#8bace0",
    ambientGround: "#344667",
    sun: "#ffead6",
    sunIntensity: 1.05,
    exposure: 1.3,
  },
  buildWorld,
};
