import buildWorld from "./neon-harbor-world.js";

// Port Lumen: a waterfront loop from the promenade, through the city and
// market, over the suspension bridge, and back via the industrial island.
export default {
  id: "neon-harbor",
  name: "Neon Harbor",
  description:
    "Port Lumen after dark: switchback streets, bridge traffic, cargo lanes and a race ferry.",
  targetLength: 1900,
  // Downtown/cargo apexes leave a ~20 m inside line: drift can clip the bend
  // while ordinary steering takes the wider lane. Bridge spans stay straight.
  minimumRadius: 28,
  edgeStyle: "port-lumen",
  // Streets reverse through downtown; the bridge crosses the inlet on a
  // straight high span before the container-yard slalom and ferry deck.
  controls: [
    [-220, 2, -170],
    [-190, 2, -195],
    [-150, 2, -209],
    [-110, 2, -214],
    [-80, 2, -201],
    [-50, 3, -179],
    [-20, 4, -164],
    [10, 4, -169],
    [40, 5, -190],
    [70, 5, -213],
    [100, 5, -217],
    [130, 6, -201],
    [158, 6, -185],
    [184, 6, -164],
    [204, 7, -141],
    [225, 7, -123],
    [250, 7, -108],
    [273, 10, -81],
    [280, 19, -45],
    [280, 27, 0],
    [280, 28, 45],
    [280, 25, 90],
    [265.52, 13, 126.256],
    [244.67999999999998, 4, 153.76],
    [215, 4, 161],
    [184, 4, 162],
    [153, 4, 163],
    [121, 4, 177],
    [91, 4, 198],
    [61, 4, 222],
    [30, 4, 240],
    [-2, 4, 244],
    [-36, 4, 244],
    [-70, 4, 242],
    [-106, 3, 232],
    [-155, 3, 210],
    [-198, 3, 181],
    [-235, 3, 146],
    [-262, 3, 105],
    [-276, 3, 59],
    [-276, 2, 12],
    [-273, 2, -35],
    [-267, 2, -79],
    [-252, 2, -122],
  ],
  sections: [
    {
      controlIndex: 0,
      id: "promenade",
      name: "HARBOR PROMENADE",
      hint: "Ride the waterfront sweep · Port Lumen ahead",
      halfWidth: 10,
      material: "asphalt",
      color: "#7af1e6",
    },
    {
      controlIndex: 4,
      id: "downtown",
      name: "DOWNTOWN SWITCHBACKS",
      hint: "Blue at the first apex · release before the reverse bend",
      halfWidth: 7.8,
      material: "asphalt",
      color: "#ed8bc6",
    },
    {
      controlIndex: 12,
      id: "market",
      name: "NIGHT MARKET",
      hint: "Thread the warm-lit stalls · bridge towers ahead",
      halfWidth: 8,
      material: "stone",
      color: "#ffbf72",
    },
    {
      controlIndex: 17,
      id: "bridge",
      name: "PORT LUMEN BRIDGE",
      hint: "Climb into the harbor view · watch the traffic",
      halfWidth: 11,
      material: "asphalt",
      color: "#8ad9ff",
    },
    {
      controlIndex: 23,
      id: "cargo",
      name: "CARGO TERMINAL",
      hint: "Set up wide · countersteer through the cargo S-bend",
      halfWidth: 7.6,
      material: "concrete",
      color: "#ffd36c",
    },
    {
      controlIndex: 30,
      id: "ferry",
      name: "RACE FERRY",
      hint: "Enter the vehicle deck · hold your line",
      halfWidth: 9.5,
      material: "concrete",
      color: "#e2a5ff",
    },
    {
      controlIndex: 35,
      id: "seawall",
      name: "SOUTH SEAWALL",
      hint: "Follow the lighthouse · waterfront cut inside",
      halfWidth: 9.5,
      material: "stone",
      color: "#72dfcf",
    },
    {
      controlIndex: 41,
      id: "boulevard",
      name: "NEON BOULEVARD",
      hint: "One last drift · the harbor comes around again",
      halfWidth: 11,
      material: "asphalt",
      color: "#c4a5ff",
    },
  ],
  // Optional maintenance hops remain on the continuous road. The bridge joint
  // plate occupies only the signed lane interval specified by its metadata.
  ramps: [
    { section: 0, fraction: 0.76, halfLength: 6, height: 1.1, offset: -6.3, halfWidth: 2 },
    { section: 3, fraction: 0.66, halfLength: 6, height: 0.55, offset: -6.5, halfWidth: 2 },
    { section: 5, fraction: 0.89, halfLength: 10, height: 1.9, offset: -3.8, halfWidth: 2.8 },
    { section: 7, fraction: 0.79, halfLength: 6, height: 0.6, offset: 6.5, halfWidth: 2 },
  ],
  bridgeJoint: { section: 3, fraction: 0.66, length: 1.2, hop: { offset: -6.5, halfWidth: 2 } },
  pads: [
    { section: 0, fraction: 0.72, offset: -6.3, duration: 0.8 },
    { section: 3, fraction: 0.86, offset: 0, duration: 0.75 },
    { section: 5, fraction: 0.85, offset: -3.8, duration: 1.05 },
    { section: 6, fraction: 0.42, offset: 5.1, duration: 0.7 },
    ...[0.3, 0.45, 0.6].map((fraction) => ({ section: 7, fraction, offset: -6.2, duration: 0.7 })),
  ],
  itemRows: [
    { section: 0, fraction: 0.28 },
    { section: 1, fraction: 0.14 },
    { section: 1, fraction: 0.88 },
    { section: 2, fraction: 0.58, offsets: [-10.8, -7, 0, 7] },
    { section: 3, fraction: 0.15 },
    { section: 4, fraction: 0.12 },
    { section: 4, fraction: 0.86 },
    { section: 5, fraction: 0.12, offsets: [-11.5, -8, 0, 8] },
    { section: 5, fraction: 0.7 },
    { section: 7, fraction: 0.48 },
  ],
  // The downtown cut and seawall rough line are ordered extensions of the
  // normal road, not disconnected routes.
  shortcut: {
    section: 1,
    startFraction: 0.34,
    endFraction: 0.69,
    extraWidth: 5,
    material: "paving",
    drag: 1.22,
  },
  verges: [
    {
      section: 2,
      startFraction: 0.22,
      endFraction: 0.74,
      side: -1,
      extraWidth: 5,
      material: "paving",
      grip: 10.2,
      drag: 0.78,
    },
    {
      section: 6,
      startFraction: 0.25,
      endFraction: 0.56,
      side: 1,
      extraWidth: 4,
      material: "paving",
      grip: 9.8,
      drag: 1.2,
    },
    {
      section: 5,
      startFraction: 0.03,
      endFraction: 0.21,
      side: -1,
      extraWidth: 4,
      material: "paving",
      grip: 11,
      drag: 0.82,
    },
  ],
  elevated: [{ section: 3, startFraction: 0.12, endFraction: 0.9 }],
  surfaces: [
    { section: 4, startFraction: 0.34, endFraction: 0.72, material: "concrete", grip: 12 },
  ],
  // Course-specific world feature descriptors consumed by the matching shared
  // systems when present. Fractions are local to their section.
  traffic: {
    section: 3,
    startFraction: 0.22,
    endFraction: 0.72,
    lanes: [1.5, 6],
    clearLane: -6.5,
    speed: 13.5,
    spacing: [45, 65],
    count: 4,
    kinds: ["sedan", "sedan", "van", "truck"],
  },
  conveyor: {
    section: 4,
    startFraction: 0.3,
    endFraction: 0.5,
    offset: 0,
    speed: 5,
    blendDistance: 3,
    fullWidth: true,
  },
  worldEvents: {
    lapTwoShip: { section: 3, fraction: 0.49, onceOnLap: 2, direction: -1 },
  },
  hazard: {
    section: 4,
    fraction: 0.84,
    kind: "cargo-shuttle",
    label: "CARGO SHUTTLE · KEEP LEFT",
    parkOffset: 12,
    minOffset: 0,
    halfWidth: 1.35,
    halfLength: 2.15,
    safeLane: -5.5,
    activation: 30,
    period: 12,
    warningSeconds: 2,
  },
  ambientSources: [
    { section: 0, fraction: 0.45, offset: -45, kind: "water", range: 90, volume: 0.08 },
    { section: 4, fraction: 0.45, offset: 20, kind: "engine", range: 90, volume: 0.13 },
    { section: 5, fraction: 0.5, offset: 20, kind: "engine", range: 80, volume: 0.12 },
    { section: 6, fraction: 0.5, offset: -30, kind: "water", range: 100, volume: 0.11 },
  ],
  theme: {
    terrain: "concrete",
    sky: "#090c23",
    fog: "#303d62",
    ground: "#4a5870",
    road: "#8d9aad",
    shoulder: "#616b83",
    hemisphere: "#b4c1ed",
    ambientGround: "#7886b1",
    ambientIntensity: 2.15,
    environmentIntensity: 0.48,
    interiorAmbientScale: 0.95,
    rimColor: "#abb6ff",
    rimIntensity: 0.5,
    roadRoughness: 0.58,
    roadMetalness: 0.08,
    roadReflectionIntensity: 0.16,
    wetPavement: true,
    lightVolume: { resolution: 256, heights: [-2, 0, 2, 4, 6, 9, 12, 16, 22, 30, 45, 75] },
    sun: "#bacdff",
    sunIntensity: 0.5,
    exposure: 1.15,
  },
  buildWorld,
};
