/** Authored pathway edges in section order. Soft shoulders are explorable;
 * drops have no invisible wall; structural walls occupy selected sides only. */
export const PATHWAY_KINDS = {
  pavement: {
    platform: true,
    mode: "soft",
    shoulder: 2,
    material: "paving",
    color: "#e9dbc6",
    height: 0,
  },
  flowers: { mode: "soft", shoulder: 9, material: "grass", color: "#90bb59", height: 0.8 },
  roots: { mode: "soft", shoulder: 6, material: "needles", color: "#785739", height: 1.3 },
  ferns: { mode: "soft", shoulder: 7, material: "needles", color: "#579373", height: 1.8 },
  rockwall: { mode: "wall", shoulder: 0, material: "stone", color: "#8f998a", height: 7 },
  cliff: { mode: "drop", shoulder: 0, material: "stone", color: "#8f998a", height: 0 },
  timber: { mode: "wall", shoulder: 0, material: "wood", color: "#886342", height: 1.1 },
  water: { mode: "drop", shoulder: 0, material: "stone", color: "#629da4", height: 0 },
  stonewall: { mode: "wall", shoulder: 0, material: "stone", color: "#c8b087", height: 4.5 },
  crops: { mode: "soft", shoulder: 8, material: "grass", color: "#9cab4d", height: 1.4 },
  hedge: { mode: "soft", shoulder: 5, material: "grass", color: "#548d60", height: 2.5 },
  hay: { mode: "soft", shoulder: 7, material: "grass", color: "#d6b161", height: 1.7 },
  planters: { mode: "soft", shoulder: 5, material: "paving", color: "#65a68a", height: 2 },
  shops: { mode: "soft", shoulder: 4, material: "paving", color: "#9c8baf", height: 3 },
  stalls: { mode: "soft", shoulder: 5, material: "paving", color: "#ce9163", height: 2.6 },
  parapet: { mode: "wall", shoulder: 0, material: "concrete", color: "#829cae", height: 1.1 },
  cargo: { mode: "soft", shoulder: 4, material: "wood", color: "#bd7956", height: 2.5 },
  deck: { mode: "drop", shoulder: 0, material: "metal", color: "#829aa4", height: 0 },
  palms: { mode: "soft", shoulder: 7, material: "sand", color: "#93a75d", height: 3 },
  dunes: { mode: "soft", shoulder: 11, material: "sand", color: "#e5c186", height: 1.3 },
  columns: { mode: "soft", shoulder: 4, material: "stone", color: "#ceb992", height: 4.5 },
  snow: { mode: "soft", shoulder: 9, material: "snow", color: "#eff3ff", height: 1.1 },
  pines: { mode: "soft", shoulder: 7, material: "snow", color: "#648e87", height: 3.6 },
  icewall: { mode: "wall", shoulder: 0, material: "ice", color: "#84cadf", height: 6 },
  chalets: { mode: "soft", shoulder: 4, material: "snow", color: "#b98979", height: 3.2 },
  gearwall: { mode: "wall", shoulder: 0, material: "metal", color: "#8e7754", height: 5.5 },
  gears: {
    platform: true,
    mode: "soft",
    shoulder: 3,
    material: "metal",
    color: "#bba16a",
    height: 2.2,
  },
  folds: {
    platform: true,
    mode: "soft",
    shoulder: 6,
    material: "paper",
    color: "#ecc7ba",
    height: 1.5,
  },
  lanterns: {
    platform: true,
    mode: "soft",
    shoulder: 4,
    material: "paper",
    color: "#df9ea9",
    height: 2.5,
  },
  paperdrop: { mode: "drop", shoulder: 0, material: "paper", color: "#fff0ce", height: 0 },
  boulders: { mode: "soft", shoulder: 5, material: "stone", color: "#748896", height: 2.5 },
  gravel: { mode: "soft", shoulder: 7, material: "gravel", color: "#a3a29a", height: 1.2 },
  crumbs: {
    platform: true,
    mode: "soft",
    shoulder: 7,
    material: "wood",
    color: "#d7b777",
    height: 0.9,
  },
  jars: {
    platform: true,
    mode: "soft",
    shoulder: 4,
    material: "wood",
    color: "#c89783",
    height: 3,
  },
  shelf: {
    platform: true,
    mode: "drop",
    shoulder: 0,
    material: "wood",
    color: "#ad855c",
    height: 0,
  },
  biscuits: {
    platform: true,
    mode: "soft",
    shoulder: 3,
    material: "wood",
    color: "#deb978",
    height: 2.4,
  },
  soap: {
    platform: true,
    mode: "soft",
    shoulder: 5,
    material: "paving",
    color: "#bedfce",
    height: 1.5,
  },
  basin: { mode: "drop", shoulder: 0, material: "paving", color: "#a8d0d8", height: 0 },
  keys: {
    platform: true,
    mode: "soft",
    shoulder: 4,
    material: "wood",
    color: "#e5d4ae",
    height: 1.7,
  },
  reeds: { mode: "soft", shoulder: 7, material: "grass", color: "#6baf9f", height: 2.6 },
  coral: { mode: "soft", shoulder: 6, material: "sand", color: "#dc9998", height: 2.7 },
  reefdrop: { mode: "drop", shoulder: 0, material: "sand", color: "#78b8b2", height: 0 },
  basaltwall: { mode: "wall", shoulder: 0, material: "stone", color: "#625566", height: 8 },
  lava: { mode: "drop", shoulder: 0, material: "stone", color: "#c18766", height: 0 },
};

export const PATHWAY_EDGES = {
  "windmill-wilds": [
    { left: "flowers", right: "flowers" },
    { left: "roots", right: "ferns" },
    { left: "rockwall", right: "cliff" },
    { left: "timber", right: "water" },
    { left: "stonewall", right: "crops" },
    { left: "crops", right: "crops" },
    { left: "hedge", right: "hedge" },
    { left: "hay", right: "flowers" },
  ],
  "neon-harbor": [
    { left: "planters", right: "water" },
    { left: "shops", right: "shops" },
    { left: "stalls", right: "stalls" },
    { left: "parapet", right: "water" },
    { left: "cargo", right: "cargo" },
    { left: "cargo", right: "deck" },
    { left: "rockwall", right: "water" },
    { left: "planters", right: "shops" },
  ],
  "sunstone-ruins": [
    { left: "palms", right: "dunes" },
    { left: "rockwall", right: "dunes" },
    { left: "rockwall", right: "cliff" },
    { left: "columns", right: "cliff" },
    { left: "stonewall", right: "columns" },
    { left: "columns", right: "columns" },
    { left: "dunes", right: "dunes" },
    { left: "palms", right: "dunes" },
  ],
  "frostpeak-festival": [
    { left: "snow", right: "snow" },
    { left: "pines", right: "snow" },
    { left: "icewall", right: "snow" },
    { left: "timber", right: "cliff" },
    { left: "snow", right: "cliff" },
    { left: "snow", right: "snow" },
    { left: "chalets", right: "chalets" },
    { left: "snow", right: "pines" },
  ],
  "clockwork-citadel": [
    { left: "cargo", right: "cargo" },
    { left: "gears", right: "deck" },
    { left: "gears", right: "deck" },
    { left: "gears", right: "deck" },
    { left: "gears", right: "deck" },
    { left: "deck", right: "deck" },
    { left: "gears", right: "deck" },
    { left: "cargo", right: "cargo" },
  ],
  "paper-revel": [
    { left: "folds", right: "folds" },
    { left: "folds", right: "folds" },
    { left: "lanterns", right: "paperdrop" },
    { left: "paperdrop", right: "paperdrop" },
    { left: "paperdrop", right: "paperdrop" },
    { left: "lanterns", right: "paperdrop" },
    { left: "folds", right: "lanterns" },
    { left: "lanterns", right: "folds" },
  ],
  "tempest-causeway": [
    { left: "boulders", right: "water" },
    { left: "deck", right: "water" },
    { left: "boulders", right: "boulders" },
    { left: "water", right: "deck" },
    { left: "boulders", right: "boulders" },
    { left: "rockwall", right: "water" },
    { left: "boulders", right: "water" },
  ],
  "pocket-pantry": [
    { left: "crumbs", right: "crumbs" },
    { left: "jars", right: "crumbs" },
    { left: "shelf", right: "shelf" },
    { left: "biscuits", right: "shelf" },
    { left: "soap", right: "basin" },
    { left: "crumbs", right: "jars" },
    { left: "shelf", right: "crumbs" },
  ],
  "railstorm-express": [
    { left: "cargo", right: "gravel" },
    { left: "rockwall", right: "cliff" },
    { left: "deck", right: "deck" },
    { left: "cargo", right: "deck" },
    { left: "cargo", right: "deck" },
    { left: "rockwall", right: "gravel" },
    { left: "gravel", right: "cargo" },
  ],
  "metronome-hall": [
    { left: "keys", right: "keys" },
    { left: "gears", right: "deck" },
    { left: "keys", right: "deck" },
    { left: "columns", right: "deck" },
    { left: "keys", right: "gears" },
    { left: "keys", right: "keys" },
  ],
  "pelagic-glasshouse": [
    { left: "planters", right: "reeds" },
    { left: "coral", right: "reefdrop" },
    { left: "coral", right: "coral" },
    { left: "coral", right: "reefdrop" },
    { left: "coral", right: "reefdrop" },
    { left: "planters", right: "reeds" },
  ],
  "emberwing-observatory": [
    { left: "boulders", right: "boulders" },
    { left: "basaltwall", right: "cliff" },
    { left: "lava", right: "lava" },
    { left: "gears", right: "cliff" },
    { left: "boulders", right: "lava" },
    { left: "boulders", right: "boulders" },
  ],
};
