import { adventure } from "./adventure-definition.js";
import { buildPantry } from "./adventure/pantry-world.js";
export default adventure({
  id: "pocket-pantry",
  name: "Pocket Pantry",
  description:
    "A breakfast-time expedition: shrink into a sunberry jar, race towering pantry shelves and a secret biscuit tunnel, then grow back beside the steaming sink.",
  points: [
    [-250, 5, -190],
    [-90, 5, -210],
    [80, 10, -140],
    [220, 24, -170],
    [290, 35, -60],
    [250, 35, 60],
    [80, 35, 70],
    [0, 22, 150],
    [100, 8, 240],
    [-70, 8, 270],
    [-240, 6, 210],
    [-180, 8, 70],
    [-280, 6, -30],
    [-320, 5, -130],
  ],
  places: [
    [0, "table", "BREAKFAST BOULEVARD", "wood"],
    [2, "portal", "SUNBERRY SHRINK JAR", "wood"],
    [4, "pantry", "THE TOWERING PANTRY", "wood", 7],
    [6, "cutlery", "SILVERWARE AND BISCUITS", "metal", 7],
    [8, "sink", "SOAP BUBBLE BASIN", "paving"],
    [10, "grow", "BACK TO BREAKFAST", "wood"],
    [12, "home", "TOAST RACK RETURN", "wood"],
  ],
  palette: ["#ffe8bd", "#e5c7a6", "#cfad87", "#e4c49c", "#578e91"],
  targetLength: 1780,
  buildWorld: buildPantry,
  staticBake: true,
  shortcut: {
    section: 6,
    startFraction: 0.1,
    endFraction: 0.8,
    extraWidth: 0.01,
    material: "wood",
  },
  scaleZones: [{ section: 2, startFraction: 0, endSection: 4, endFraction: 0.96, scale: 0.28 }],
  verges: [
    {
      section: 3,
      startFraction: 0.15,
      endFraction: 0.8,
      side: -1,
      extraWidth: 5,
      material: "wood",
      grip: 12,
      drag: 0.7,
      driveable: true,
      maxScale: 0.45,
    },
  ],
  elevated: Array.from({ length: 7 }, (_, section) => ({
    section,
    startFraction: 0,
    endFraction: 1,
  })),
  ambientSources: [
    { section: 0, fraction: 0.48, offset: 28, kind: "steam", range: 85, volume: 0.12 },
    { section: 2, fraction: 0.48, offset: -26, kind: "wood", range: 55, volume: 0.08 },
    { section: 4, fraction: 0.45, offset: 31, kind: "drip", range: 90, volume: 0.16 },
    { section: 6, fraction: 0.2, offset: -40, kind: "birds", range: 160, volume: 0.05 },
  ],
  theme: {
    sky: "#ffe8bd",
    fog: "#e5c7a6",
    ground: "#cfad87",
    road: "#e4c49c",
    shoulder: "#578e91",
    hemisphere: "#cce6ec",
    ambientGround: "#98776d",
    ambientIntensity: 0.75,
    sun: "#fff0c7",
    sunIntensity: 3,
    sunPosition: [-110, 70, -45],
    exposure: 1.12,
    groundHeight: -22,
    terrain: "wood",
    fogFar: 980,
    cameraFar: 1200,
    lightVolume: {
      resolution: 128,
      columns: 3,
      rows: 2,
      heights: [-20, 0, 15, 30, 45, 70],
      strength: 1.2,
    },
  },
});
