import { withCourseExperience } from "./experiences/definitions.js";
import { PATHWAY_EDGES } from "./pathway-edges.js";
import { adventure } from "./adventure-definition.js";
import { buildRailstorm } from "./adventure/railstorm-world.js";
const course = adventure({
  id: "railstorm-express",
  pathwayEdges: PATHWAY_EDGES["railstorm-express"],
  name: "Railstorm Express",
  description:
    "Chase the express along the cliffs, board its moving freight decks, race through cargo, and burst back onto the mountain road.",
  points: [
    [-340, 5, -160],
    [-205, 6, -245],
    [-35, 10, -200],
    [140, 18, -100],
    [265, 28, 0],
    [300, 28, 120],
    [170, 25, 200],
    [15, 24, 200],
    [-150, 24, 195],
    [-300, 21, 160],
    [-400, 12, 30],
    [-275, 8, -25],
    [-155, 6, 35],
    [-80, 5, -70],
    [-240, 5, -95],
  ],
  places: [
    [0, "station", "IRONVALE STATION", "paving"],
    [2, "chase", "CLIFFSIDE CHASE", "gravel"],
    [4, "boarding", "BOARD THE EXPRESS", "wood", 7],
    [6, "train", "MOVING FREIGHT DECK", "wood", 7],
    [8, "cargo", "CARGO CARAVAN", "wood", 7],
    [10, "tunnel", "TUNNEL DISEMBARK", "stone"],
    [12, "home", "SWITCHYARD RETURN", "gravel"],
  ],
  ramps: [
    { section: 1, fraction: 0.64, halfLength: 10, height: 0.7 },
    { section: 6, fraction: 0.6, halfLength: 12, height: 0.8 },
  ],
  palette: ["#a3b5c2", "#8b9aaf", "#657279", "#c5bfa8", "#bf744b"],
  targetLength: 1900,
  buildWorld: buildRailstorm,
  movingDecks: [
    {
      id: "ironvale-express",
      section: 2,
      startFraction: 0.08,
      endSection: 4,
      endFraction: 0.92,
      speed: 9,
      carLength: 24,
      suspension: 0.18,
    },
  ],
  staticBake: true,
  shortcut: {
    section: 6,
    startFraction: 0.15,
    endFraction: 0.75,
    extraWidth: 0.01,
    material: "gravel",
  },
  verges: [
    {
      section: 1,
      startFraction: 0.1,
      endFraction: 0.65,
      side: -1,
      extraWidth: 6,
      material: "gravel",
      grip: 10,
      driveable: true,
      drag: 1.1,
    },
  ],
  theme: {
    sky: "#a3b5c2",
    fog: "#9aa5b1",
    ground: "#526570",
    road: "#c5bfa8",
    shoulder: "#bf744b",
    hemisphere: "#b6d5e3",
    ambientGround: "#536173",
    ambientIntensity: 0.8,
    sun: "#ffe2b5",
    sunIntensity: 2.8,
    sunPosition: [-90, 80, -55],
    exposure: 1.1,
    terrain: "gravel",
    groundHeight: -25,
    fogFar: 950,
    cameraFar: 1150,
    lightVolume: {
      resolution: 128,
      columns: 3,
      rows: 2,
      heights: [-20, 0, 15, 30, 45, 70],
      strength: 1.2,
    },
  },
  ambientSources: [
    { section: 0, fraction: 0.3, offset: -35, kind: "engine", range: 110, volume: 0.12 },
    { section: 3, fraction: 0.5, offset: 0, kind: "engine", range: 180, volume: 0.15 },
    { section: 5, fraction: 0.2, offset: 23, kind: "steam", range: 80, volume: 0.08 },
  ],
  elevated: [2, 3, 4].map((section) => ({ section, startFraction: 0, endFraction: 1 })),
});

export default withCourseExperience(course);
