export const LANDMARKS=[
 {id:'brookfield',name:'Brookfield Place',lon:-74.0163,lat:40.7132,description:'Glass above, river below. A good place to watch the light.',kind:'glass'},
 {id:'battery',name:'The Battery',lon:-74.0169,lat:40.7034,description:'Salt in the air, ferries on the water, and nowhere to hurry.',kind:'park'},
 {id:'wtc',name:'One World Trade Center',lon:-74.01338,lat:40.7130,description:'A silver needle, stitching the city to the sky.',kind:'tower'},
 {id:'trinity',name:'Trinity Church',lon:-74.0121,lat:40.7081,description:'A quiet churchyard in the middle of the bustle.',kind:'church'},
 {id:'seaport',name:'South Street Seaport',lon:-74.0022,lat:40.7068,description:'Old brick, wooden decks, and the smell of the harbor.',kind:'harbor'},
 {id:'bridge',name:'Brooklyn Bridge',lon:-73.9992,lat:40.7081,description:'Two stone towers and a thousand threads across the water.',kind:'bridge'},
 {id:'cityhall',name:'City Hall Park',lon:-74.0060,lat:40.7129,description:'A patch of green where a little bird can disappear.',kind:'park'},
 {id:'washington',name:'Washington Square',lon:-73.9973,lat:40.7308,description:'A marble arch, a fountain, a song drifting between trees.',kind:'arch'},
 {id:'highline',name:'The High Line',lon:-74.0048,lat:40.7397,description:'A garden in the air. Almost as if it were made for birds.',kind:'garden'},
 {id:'flatiron',name:'Flatiron Building',lon:-73.9896,lat:40.7411,description:'A little wedge of Manhattan, pointed into the breeze.',kind:'wedge'},
 {id:'empire',name:'Empire State Building',lon:-73.9857,lat:40.7484,description:'Climb above the avenues and let the whole city breathe.',kind:'tower'},
 {id:'bryant',name:'Bryant Park',lon:-73.9832,lat:40.7536,description:'Chairs in the shade. A crumb beneath every table.',kind:'park'},
];
export const MOMENTS=[
 {id:'cart',type:'food',name:'A bagel for the road',lon:-74.0161,lat:40.7140,detail:'Pick up a fallen sesame bite. E to carry; P to peck.',item:'sesame bagel',prop:'vendor'},
 {id:'picnic',type:'food',name:'A generous picnic',lon:-74.0168,lat:40.7035,detail:'Someone left a crust beside the bench.',item:'picnic crust',prop:'bench'},
 {id:'bakery',type:'food',name:'The early bakery',lon:-74.0117,lat:40.7075,detail:'Warm crumbs tumble out of a paper bag.',item:'bakery crumb',prop:'vendor'},
 {id:'seeds',type:'food',name:'A pocketful of seeds',lon:-74.0061,lat:40.7130,detail:'The park regular always saves a few for the birds.',item:'sunflower seeds',prop:'bench'},
 {id:'pretzel',type:'food',name:'A pretzel afternoon',lon:-73.9978,lat:40.7308,detail:'A salty little snack beside the square.',item:'pretzel piece',prop:'vendor'},
 {id:'uptown',type:'food',name:'Under a café chair',lon:-73.9840,lat:40.7535,detail:'A buttery bite from a very busy human.',item:'croissant flake',prop:'bench'},
 {id:'button',type:'shiny',name:'The blue button',lon:-74.0178,lat:40.7108,detail:'A tiny sky-colored button. It would look lovely at home.',item:'blue button',prop:'planter'},
 {id:'ring',type:'shiny',name:'A little gold glimmer',lon:-74.0026,lat:40.7071,detail:'A lost brass loop, warm in the afternoon light.',item:'brass loop',prop:'bench'},
 {id:'glass',type:'shiny',name:'Sea glass',lon:-74.0180,lat:40.7059,detail:'The river has made this green shard smooth.',item:'sea glass',prop:'planter'},
 {id:'ribbon',type:'shiny',name:'A ribbon on the breeze',lon:-74.0080,lat:40.7202,detail:'A florist’s ribbon for a softer nest.',item:'florist ribbon',prop:'planter'},
 {id:'vent',type:'updraft',name:'The city breathes',lon:-74.0151,lat:40.7120,detail:'Fly through the warm steam for a gentle lift.',prop:'vent'},
 {id:'vent2',type:'updraft',name:'A rising little breeze',lon:-74.0108,lat:40.7095,detail:'A warm shortcut above the street.',prop:'vent'},
 {id:'bath',type:'bath',name:'A very small bath',lon:-74.0168,lat:40.7048,detail:'Ruffle your feathers in the fountain. E to splash.',prop:'fountain'},
 {id:'busker',type:'music',name:'A song between buildings',lon:-74.0173,lat:40.7131,detail:'Stay beside the musician and listen. E to sing along.',prop:'busker'},
 {id:'garden',type:'garden',name:'The rooftop gardener',lon:-74.0169,lat:40.7146,detail:'Help scatter a few seeds. A flower grows for each visit.',prop:'garden',roof:true},
 {id:'laundry',type:'rest',name:'Laundry in the sunlight',lon:-74.0098,lat:40.7189,detail:'Perch beside the washing. E to rest in the warm breeze.',prop:'laundry',roof:true},
 {id:'friend',type:'friend',name:'A familiar little face',lon:-74.0167,lat:40.7138,detail:'Coo hello with E or Q. Bring food home to grow your flock.',prop:'friend'},
];
export const INTENTIONS=[
 ['Bring a small bite home.','The bagel cart is a short flight from your nest.'],
 ['Make room for a friend.','Two bites at home will welcome your first companion.'],
 ['Keep a memory of the city.','Fly close to three landmarks to fill your scrapbook.'],
 ['Find something that catches the light.','A blue button, a brass loop, a piece of sea glass…'],
 ['Let the city lift you.','Fly through a curl of warm steam near Brookfield.'],
 ['A little splash, a little song.','Find the fountain and the waterfront musician.'],
 ['Make this ledge a home.','Four bites, three treasures, six memories, and a warm breeze.'],
 ['You belong here.','Your home is full of little stories. The city is still yours.'],
];
