import * as THREE from '../vendor/three.module.js';
const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function illustration(l,found){
 const color=found?'#829c89':'#b6c1ab';let art='';
 if(l.kind==='tower')art='<path d="M103 122V43L110 31H127L134 43V122ZM118 31V10" fill="#769496" stroke="#5f7f81" stroke-width="2"/><path d="M106 43H131L126 121H111Z" fill="#9bb4b0"/>';
 else if(l.kind==='bridge')art='<path d="M0 107H240M38 107V47H70V107M169 107V47H201V107M0 96Q54 48 120 88Q185 48 240 96" fill="none" stroke="#849684" stroke-width="5"/><path d="M50 107V57M184 107V57" stroke="#c9d2b5" stroke-width="9"/>';
 else if(l.kind==='arch')art='<path d="M82 122V55H156V122H135V86Q118 61 102 86V122ZM77 55H161V44H77Z" fill="#d2c8a4"/>';
 else if(l.kind==='wedge')art='<path d="M90 126V31L147 59V126Z" fill="#b4ad8e"/><path d="M90 31L103 36V126H90Z" fill="#d2c6a4"/><path d="M112 56V117M128 64V117M141 70V117" stroke="#89958a" stroke-width="2"/>';
 else if(l.kind==='church')art='<path d="M83 125V85H100V51L118 13L136 51V85H153V125Z" fill="#a4a38a"/><path d="M108 125V94Q118 79 128 94V125" fill="#728a80"/>';
 else if(l.kind==='glass')art='<path d="M48 123V55H98V28H153V70H195V123Z" fill="#99b4ad"/><path d="M54 78Q121 6 189 78V124H54Z" fill="#afc6b7" stroke="#6d9693" stroke-width="2"/><path d="M87 50V121M120 39V121M153 51V121M58 79H187M57 99H189" stroke="#d6dfc5" stroke-width="2"/>';
 else if(l.kind==='harbor')art='<path d="M35 115V77H109V115M135 115V63H201V115" fill="#af9b7e"/><path d="M27 78L73 48L117 78M126 64L167 38L210 64" fill="#b4a589"/><path d="M15 129H225" stroke="#78998e" stroke-width="4"/>';
 else art='<path d="M0 126Q120 83 240 126V160H0Z" fill="#bac9a3"/><path d="M57 126V66M178 125V63" stroke="#8f9c77" stroke-width="5"/><circle cx="57" cy="68" r="28" fill="#95ad80"/><circle cx="178" cy="61" r="34" fill="#9bb386"/><path d="M75 133Q120 78 164 132" fill="none" stroke="#e6ddbd" stroke-width="8"/>';
 return `<svg viewBox="0 0 240 160" role="img" aria-label="Illustration of ${escape(l.name)}"><rect width="240" height="160" fill="#dce2ca"/><circle cx="186" cy="33" r="17" fill="#edcf99"/><path d="M0 130V100H18V85H40V117H54V92H73V131M156 130V100H181V112H208V89H233V125H240" fill="${color}" opacity=".4"/><path d="M0 143H240V160H0Z" fill="#adbfaf"/>${art}<path d="M29 32q4-5 8 0q4-5 8 0M44 45q3-4 6 0q3-4 6 0" fill="none" stroke="#7c947e" stroke-width="1.5"/></svg>`;
}
export class GameInterface {
 constructor(options){Object.assign(this,options);this.lastHud=0;this.lastFocus=null;}
 update(){const {life,flight}=this;const p=flight.position;const index=life.intention,text=life.intentionText;
  $('intention').textContent=text[0];$('intention-detail').textContent=life.target?this.destinationText():text[1];$('bag').textContent=life.save.carried?`◌ ${life.save.carried.item}`:'◌ Nothing in your beak';$('flock-count').textContent=`${life.friends+1} little bird${life.friends?'s':''}`;
  const atHome=p.distanceTo(this.nest)<6&&!flight.flying;
  $('context').hidden=!atHome&&(!life.nearby||flight.flying);
  if(atHome){$('context-title').textContent=life.save.carried?'Bring this little find home':'Your Hudson-side nest';$('context-detail').textContent=life.save.carried?'Settle in and share it.':'A quiet ledge, and room for a friend.';}
  else if(life.nearby&&!flight.flying){$('context-title').textContent=life.nearby.name;$('context-detail').textContent=life.nearby.detail;}
  const lat=-p.z/110540+40.72,lon=p.x/84360-74;
  let district=lat>40.746?'MIDTOWN SOUTH':lat>40.735?'CHELSEA & FLATIRON':lat>40.725?'GREENWICH VILLAGE':lat>40.718?'SOHO & TRIBECA':lon< -74.014?'BATTERY PARK CITY':'FINANCIAL DISTRICT';
  if(!this.map.onLand(p.x,p.z)&&this.map.surface(p.x,p.z)===0)district=lon< -74.01?'HUDSON RIVER':'NEW YORK HARBOR';
  $('district').textContent=district;$('map-location').textContent=life.target?life.target.name:district.toLowerCase();
  if(atHome){$('mode').textContent='AT HOME';$('mode-icon').textContent='⌂';}else $('mode-icon').textContent=flight.flying?'⌁':'·';
  if(index!==this.lastIntention){this.lastIntention=index;if(index>0)this.toast(index===7?'A home full of stories. Keep wandering.':`A new little intention: ${text[0]}`);}
 }
 destinationText(){const t=this.life.target,p=this.flight.position,d=Math.hypot(p.x-t.position.x,p.z-t.position.z),angle=Math.atan2(-(t.position.x-p.x),-(t.position.z-p.z)),delta=THREE.MathUtils.euclideanModulo(angle-this.flight.heading+Math.PI,2*Math.PI)-Math.PI;const direction=Math.abs(delta)<.35?'ahead':Math.abs(delta)>2.6?'behind you':delta>0?'to your left':'to your right';return `${t.name} · ${d>1000?(d/1000).toFixed(1)+' km':Math.round(d)+' m'} ${direction}`;}
 track(target){this.life.target=target;this.closeModal();this.toast(`Follow your curiosity toward ${target.name}. The map will guide you.`);}
 album(){const {life}=this;const s=life.save;
  this.openModal('Your scrapbook','LITTLE THINGS, KEPT CLOSE',`<p>${s.visited.length} of ${life.landmarks.length} places remembered. Fly close to a landmark to keep its postcard. Press <kbd>C</kbd> to keep your own photograph.</p><div class="album-grid">${life.landmarks.map(l=>{const found=s.visited.includes(l.id);return `<article class="postcard ${found?'':'locked'}">${illustration(l,found)}<h3>${escape(l.name)}</h3><p>${found?escape(l.description):'A little memory, waiting to happen.'}</p><button data-landmark="${l.id}">${found?'Visit again':'Follow the breeze here'} →</button></article>`;}).join('')}</div>${s.photos.length?'<h3 class="photo-heading">Through a little bird’s eyes</h3><div class="photo-grid">'+s.photos.map((p,i)=>`<article><img src="${p.src}" alt="Your view over Manhattan"><p>${escape(p.caption)}</p><button data-photo="${i}">Save photograph ↓</button></article>`).join('')+'</div>':''}`);
  for(const b of $('modal-content').querySelectorAll('[data-landmark]'))b.onclick=()=>this.track(life.landmarks.find(l=>l.id===b.dataset.landmark));
  for(const b of $('modal-content').querySelectorAll('[data-photo]'))b.onclick=()=>{const a=document.createElement('a');a.href=s.photos[+b.dataset.photo].src;a.download='birdway-memory.jpg';a.click();};
 }
 journal(){const {life}=this,s=life.save;
  this.openModal('A little field guide','GO AT YOUR OWN PACE',`${life.completed?'<div class="completion"><h3>You belong here.</h3>Your nest is full of lovely things and familiar faces. There is no finish line. Take another sunset flight.</div>':''}<p>A bird’s life is made of small things. Carry a bite or a shiny find with <kbd>E</kbd>, then return to the nest and press <kbd>E</kbd> to share it. Every two bites welcomes a companion. Progress is kept in this browser.</p><div class="stats"><div><strong>${s.food}</strong>bites shared</div><div><strong>${s.treasures.length}</strong>lovely finds</div><div><strong>${life.friends+1}</strong>little birds</div><div><strong>${(s.distance/1000).toFixed(1)}</strong>km wandered</div></div><div class="guide-list">${life.moments.map(m=>`<article class="guide-item"><h3>${escape(m.name)} ${s.moments.includes(m.id)?'·':''}</h3><p>${escape(m.detail)}</p><button data-moment="${m.id}">${s.moments.includes(m.id)?'Wander back':'Take a little outing'} →</button></article>`).join('')}</div><p><kbd>W S</kbd> climb / descend · <kbd>A D</kbd> bank / turn · <kbd>SPACE</kbd> take off / flap · <kbd>SHIFT</kbd> fast glide · <kbd>E</kbd> land / interact · <kbd>P</kbd> peck · <kbd>Q</kbd> coo · <kbd>H</kbd> return home · <kbd>C</kbd> photograph · <kbd>TAB</kbd> map · <kbd>ESC</kbd> pause.<br><br>On a street or rooftop, W / S waddle forward and back. Walk off a ledge to spread your wings automatically. Flight has no damage, hunger meter or fail state. A gamepad’s left stick steers; A / Cross flaps; right trigger glides.</p>`);
  for(const b of $('modal-content').querySelectorAll('[data-moment]'))b.onclick=()=>this.track(life.moments.find(m=>m.id===b.dataset.moment));
 }
 photo(){this.renderer.render(this.scene,this.camera);const canvas=document.createElement('canvas');canvas.width=960;canvas.height=Math.round(this.renderer.domElement.height/this.renderer.domElement.width*960);const c=canvas.getContext('2d');c.drawImage(this.renderer.domElement,0,0,canvas.width,canvas.height);const caption=$('district').textContent.toLowerCase()+' · '+$('clock').textContent;this.life.save.photos.push({src:canvas.toDataURL('image/jpeg',.72),caption});this.life.save.photos=this.life.save.photos.slice(-6);this.life.persist();this.toast('A little view, kept close. Find your photograph in the scrapbook.');}
 mapMarkers(canvas,scale,center){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.save();ctx.translate(w/2,h/2);
  const point=(p,color,size)=>{const x=(p.x-center.x)*scale,z=(p.z-center.z)*scale;if(Math.abs(x)<w/2-5&&Math.abs(z)<h/2-5){ctx.beginPath();ctx.arc(x,z,size,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}};
  for(const m of this.life.moments)point(m.position,m.type==='shiny'?'#bf9c59':m.type==='food'?'#768858':'#899a80',2.2);
  for(const l of this.life.landmarks)point(l.position,this.life.save.visited.includes(l.id)?'#698a83':'#92987b',3);
  if(this.life.target){const p=this.life.target.position,x=THREE.MathUtils.clamp((p.x-center.x)*scale,-w/2+10,w/2-10),z=THREE.MathUtils.clamp((p.z-center.z)*scale,-h/2+10,h/2-10);ctx.strokeStyle='#9c7946';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,z,6,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b59660';ctx.beginPath();ctx.arc(x,z,2.5,0,Math.PI*2);ctx.fill();}ctx.restore();
 }
 mapDialog(){this.openModal('All those little places','MANHATTAN, BELOW 59TH',`<p>Twenty thousand real building footprints. One small bird. Choose a place to follow; travel at your own pace.</p><canvas id="full-map" width="1200" height="600" aria-label="Map of Manhattan with numbered landmarks"></canvas><div class="map-legend"><span>▲ your bird</span><span>● landmark</span><span>◌ your nest</span><span>✧ little discovery</span></div><div class="map-list">${this.life.landmarks.map((l,i)=>`<button data-landmark="${l.id}">${i+1}. ${escape(l.name)}</button>`).join('')}<button id="track-nest">Your nest</button></div>`);this.paintFullMap();for(const b of $('modal-content').querySelectorAll('[data-landmark]'))b.onclick=()=>this.track(this.life.landmarks.find(l=>l.id===b.dataset.landmark));$('track-nest').onclick=()=>this.track({name:'Your Hudson-side nest',position:this.nest});}
 paintFullMap(){const canvas=$('full-map'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,c=new THREE.Vector3(550,0,-1650),scale=.072;
  ctx.fillStyle='#c2d4c8';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(scale,scale);ctx.translate(-c.x,-c.z);
  for(const p of this.map.land){ctx.beginPath();for(const r of p.rings){r.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();}ctx.fillStyle=p.name==='Manhattan'?'#e5e5cf':'#ced9c3';ctx.fill('evenodd');}
  ctx.strokeStyle='#c4cdb8';ctx.lineWidth=14;ctx.beginPath();for(const s of this.map.streets)s.points.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.stroke();
  ctx.fillStyle='#b7c2aa';for(const b of this.map.buildings){ctx.beginPath();b.rings[0].forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.fill();}ctx.restore();
  this.mapMarkers(canvas,scale,c);ctx.fillStyle='#a1814c';ctx.beginPath();ctx.arc(w/2+(this.nest.x-c.x)*scale,h/2+(this.nest.z-c.z)*scale,6,0,Math.PI*2);ctx.fill();
  const p=this.flight.position;ctx.save();ctx.translate(w/2+(p.x-c.x)*scale,h/2+(p.z-c.z)*scale);ctx.rotate(-this.flight.heading);ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(-6,6);ctx.lineTo(0,3);ctx.lineTo(6,6);ctx.fillStyle='#455f48';ctx.fill();ctx.restore();
  this.life.landmarks.forEach((l,i)=>{const x=w/2+(l.position.x-c.x)*scale,y=h/2+(l.position.z-c.z)*scale;ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fillStyle='#f7f1de';ctx.fill();ctx.strokeStyle='#8a9c82';ctx.stroke();ctx.font='12px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#4e6850';ctx.fillText(i+1,x,y);});
  ctx.font='12px sans-serif';ctx.textAlign='left';ctx.fillStyle='#6b8778';ctx.fillText('HUDSON RIVER',w*.20,h*.48);ctx.fillText('EAST RIVER',w*.58,h*.55);ctx.fillText('N ↑',w-45,25);
 }
}
